trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals reem-ubuntu

steps:
# Step 1: Use the .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

# Step 2: Restore dependencies
- script: |
    dotnet restore
  displayName: 'Restore Dependencies'

# Step 3: Build the project
- script: |
    dotnet build --configuration Release
  displayName: 'Build Project'

# Step 4: Pack the project (create NuGet package)
- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: 'Pack Project as NuGet Package'

# Step 5: Push the package to Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishFeed: 'HelloWorldAppArtifacts'  # Name of your Azure Artifacts feed
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    allowPackageConflicts: true  # This allows overwriting existing versions if necessary
