trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals reem-ubuntu

steps:
# Use the .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

# Build and publish the project
- script: |
    dotnet build
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build Project'

# Publish the build as a pipeline artifact
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'

# Publish the build to Azure Artifacts feed
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.ArtifactStagingDirectory)'
    feedsToUse: 'internal'
    vstsFeed: 'HelloWorldAppArtifacts'  # Your feed ID from the URL
    packageName: 'HelloWorldApp'
    packageVersion: '1.0.$(Build.BuildId)'
