trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals reem-ubuntu

variables:
  projectName: 'HelloWorldApp'
  packageVersion: '1.0.$(Build.BuildId)'
  feedName: 'HelloWorldAppArtifacts'

steps:
# Step 1: Use the .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

# Step 2: Restore dependencies
- script: |
    dotnet restore HelloWorldApp.sln
  displayName: 'Restore Dependencies'

# Step 3: Build the project
- script: |
    dotnet build --configuration Release
  displayName: 'Build Project'

# Step 4: Pack the project (create NuGet package)
- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)
  displayName: 'Pack Project as NuGet Package'

# Step 5: Push the package to Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishFeed: 'HelloWorldAppArtifacts'  # Use the correct feed name
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    allowPackageConflicts: true
    externalFeedUrl: 'https://pkgs.dev.azure.com/reemnu/HelloWorldAppPipeline/_packaging/HelloWorldAppArtifacts/nuget/v3/index.json'
