trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals reem-ubuntu

variables:
  projectName: 'HelloWorldApp'
  packageVersion: '1.0.$(Build.BuildId)'
  feedName: 'HelloWorldAppArtifacts'

steps:
# Step 1: Use the .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

# Step 2: Authenticate with Azure Artifacts
- task: NuGetAuthenticate@0
  displayName: 'Authenticate with Azure Artifacts'

# Step 3: Restore dependencies using dotnet restore
- script: |
    dotnet restore HelloWorldApp.sln
  displayName: 'Restore Dependencies'

# Step 4: Build the project using dotnet build
- script: |
    dotnet build --configuration Release
  displayName: 'Build Project'

# Step 5: Pack the project (create NuGet package) using dotnet pack
- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)
  displayName: 'Pack Project as NuGet Package'

# Step 6: Push the package to Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishFeed: '$(feedName)'  # This should reference the feed in Azure Artifacts
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    allowPackageConflicts: true
