trigger:
- master

pool:
  name: Default
  demands:
    - agent.name -equals reem-ubuntu

variables:
  projectName: 'HelloWorldApp'
  packageVersion: '1.0.$(Build.BuildId)'
  feedName: 'HelloWorldAppArtifacts'

steps:
# Step 1: Use the .NET SDK
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

# Step 2: Restore dependencies
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'

# Step 3: Build the project
- script: |
    dotnet build --configuration Release
  displayName: 'Build Project'

# Step 4: Pack the project (create NuGet package)
- script: |
    dotnet pack --configuration Release --output $(Build.ArtifactStagingDirectory) /p:PackageVersion=$(packageVersion)
  displayName: 'Pack Project as NuGet Package'

# Step 5: Push the package to Azure Artifacts feed
- task: NuGetCommand@2
  inputs:
    command: 'push'
    publishFeed: '$(feedName)'  # Use the variable for the feed name
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'
    allowPackageConflicts: true
