trigger:
- master

pool:
  name: HostedServerPool

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.108'

- script: |
    dotnet build
    dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
  displayName: 'Build Project'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)'
    artifact: 'drop'
    publishLocation: 'pipeline'
